Repository spacemeshos/smapp, pull requests merged in 2023-11, with the labels that each got.

#1573 Release v1.2.5
  node/use-version
  package.json
Labels: Type: Release

#1579 Add link to POS proving docs on PosProfiler screen
  app/components/node/PoSProfiler.tsx
  shared/constants.ts
Labels: enhancement

#1582 fix: check if empty rewards list before render
  app/components/node/SmesherLog.tsx
Labels: bug

#1587 Make wallet file guards less strict
  shared/types/guards.ts
Labels: bug

#1590 Fix: display informative node errors
  app/basicComponents/ErrorMessage.tsx
  app/redux/node/reducer.ts
  app/screens/network/Network.tsx
  desktop/NodeManager.ts
  desktop/main/reactions/handleSmesherIpc.ts
  desktop/main/startApp.ts
  desktop/utils.ts
Labels: bug
