Repository spacemeshos/smapp, pull requests merged in 2023-04, with the labels that each got.

#1209 Fix macos autoupdate (x64)
  .github/workflows/release.yml
  .gitignore
  node/use-version
  scripts/packagerScript.ts
Labels: bug

#1218 Start smeshing without calling GRPC API
  app/redux/smesher/actions.ts
  app/screens/node/NodeSetup.tsx
  desktop/NodeManager.ts
  desktop/main/smeshingOpts.ts
Labels: bug

#1220 Release hotfix 0.3.2
  desktop/SmesherManager.ts
  desktop/main/constants.ts
  desktop/main/smeshingOpts.ts
  package.json
Labels: bug, release

#1186 Feature: Filters and NOnce
  app/components/transactions/TransactionsMeta.tsx
  app/redux/wallet/selectors.ts
  app/screens/transactions/Transactions.tsx
Labels: Type: Feature

#1231 Release Smapp v0.3.4
  node/use-version
  package.json
Labels: Type: Release

#1236 "Open a wallet from a wallet file" screen colors
  app/screens/auth/FileRestore.tsx
  app/theme/variants/modern.ts
Labels: enhancement
