Repository spacemeshos/smapp, pull requests merged in 2023-07, with the labels that each got.

#1329 Show SmesherID as hex-encoded key
  app/components/common/Address.tsx
  app/screens/node/Node.tsx
  desktop/SmesherService.ts
  proto/activation.proto
  proto/activation.ts
  proto/activation_types.proto
  proto/activation_types.ts
  proto/admin.proto
  proto/admin.ts
  proto/admin_types.proto
  proto/admin_types.ts
  proto/debug.proto
  proto/debug.ts
  proto/debug_types.proto
  proto/debug_types.ts
  proto/gateway.proto
  proto/gateway.ts
  proto/gateway_types.proto
  proto/gateway_types.ts
  proto/google/protobuf/Duration.ts
  proto/google/protobuf/Timestamp.ts
  proto/google/protobuf/timestamp.proto
  proto/node.proto
  proto/node.ts
  proto/node_types.proto
  proto/node_types.ts
  proto/smesher_types.proto
  proto/spacemesh/v1/AccountsRequest.ts
  proto/spacemesh/v1/ActivationService.ts
  proto/spacemesh/v1/AdminService.ts
  proto/spacemesh/v1/CheckpointStreamRequest.ts
  proto/spacemesh/v1/CheckpointStreamResponse.ts
  proto/spacemesh/v1/DebugService.ts
  proto/spacemesh/v1/Event.ts
  proto/spacemesh/v1/EventAtxPubished.ts
  proto/spacemesh/v1/EventBeacon.ts
  proto/spacemesh/v1/EventEligibilities.ts
  proto/spacemesh/v1/EventInitComplete.ts
  proto/spacemesh/v1/EventInitStart.ts
  proto/spacemesh/v1/EventPoetWaitProof.ts
  proto/spacemesh/v1/EventPoetWaitRound.ts
  proto/spacemesh/v1/EventPostComplete.ts
  proto/spacemesh/v1/EventPostStart.ts
  proto/spacemesh/v1/EventProposal.ts
  proto/spacemesh/v1/EventStreamRequest.ts
  proto/spacemesh/v1/GatewayService.ts
  proto/spacemesh/v1/HighestResponse.ts
  proto/spacemesh/v1/NodeInfoResponse.ts
  proto/spacemesh/v1/NodeService.ts
  proto/spacemesh/v1/ProposalEligibility.ts
  proto/spacemesh/v1/RecoverRequest.ts
  proto/spacemesh/v1/SmesherIDResponse.ts
  proto/spacemesh/v1/VerifyChallengeRequest.ts
  proto/spacemesh/v1/VerifyChallengeResponse.ts
Labels: bug, milestone/genesis

#1335 Use proper HRP network defined by node config
  desktop/main.dev.ts
  desktop/main/reactions/syncToRenderer.ts
  desktop/main/reactions/views/walletView.ts
  desktop/main/startApp.ts
  desktop/testMode.ts
  shared/types/node.ts
Labels: milestone/genesis

#1339 fix: use genesisID in custom config name
  desktop/SmesherManager.ts
  desktop/main/NodeConfig.ts
  desktop/main/reactions/spawnManagers.ts
  desktop/main/reactions/syncNodeConfig.ts
  desktop/main/startApp.ts
  tests/nodeConfig.spec.ts
Labels: bug

#1341 Fix: do not ask switch the network twice on unlocking wallet
  app/components/common/Version.tsx
  app/screens/auth/SwitchNetwork.tsx
  app/screens/auth/UnlockWallet.tsx
  desktop/main/reactions/ensureNetwork.ts
  desktop/main/sources/wallet.ipc.ts
Labels: bug, UX

#1361 Fix: put `smeshing-opts-compute-batch-size` in a correct place in Config
  desktop/SmesherManager.ts
Labels: bug

#1362 Fix: don't restart node every hour
  README.md
  desktop/main/sources/fetchDiscovery.ts
  desktop/main/startApp.ts
Labels: bug

#1327 Use `setWindowOpenHandler()` in favor of deprecated `new-window` event
  desktop/main/createWindow.ts
  desktop/main/reactions/handleOpenDashboard.ts
Labels: bug

#1342 feat/1310: fix sending to same addreess
  app/basicComponents/ErrorPopup.tsx
  app/components/contacts/utils.ts
  app/components/wallet/TxParams.tsx
  app/screens/wallet/SendCoins.tsx
  app/theme/colors.ts
  app/theme/variants/dark.ts
  app/theme/variants/light.ts
  app/theme/variants/modern.ts
Labels: bug

#1326 fix: update smeshing metadata and return empty object if no file exists
  desktop/SmesherMetadataUtils.ts
Labels: bug

#1371 fix: issue with ResizeObserver loop limit exceeded
  app/basicComponents/DropDown.tsx
  app/hooks/useClickAway.ts
  app/index.tsx
  package.json
  yarn.lock
Labels: bug
