Repository spacemeshos/smapp, pull requests merged in 2023-06, with the labels that each got.

#1269 fix(): fix PoS skip button
  app/components/node/PoSDirectory.tsx
  app/components/node/PoSFooter.tsx
  app/screens/node/NodeSetup.tsx
Labels: bug

#1268 Autocompleted dropdown list (Addresses)-add scrolling
  app/basicComponents/AutocompleteDropdown.tsx
  app/screens/contacts/Contacts.tsx
Labels: enhancement

#1266 feat(): add index for mnemonic words
  app/screens/auth/WordsRestore.tsx
  app/screens/backup/TwelveWordsBackup.tsx
Labels: enhancement

#1271 Release v0.3.7
  desktop/posProfiler.ts
  node/use-version
  package.json
Labels: release

#1272 Add test mode, which runs go-spacemesh in standalone mode
  README.md
  desktop/main.dev.ts
  desktop/main/Networks.ts
  desktop/testMode.ts
  desktop/utils.ts
Labels: feature

#1282 fix: update validation for wallet name, include upper case and spaces for the consistency with default wallet name
  app/components/wallet/AccountsOverview.tsx
  app/screens/auth/Validation.tsx
  desktop/main/Wallet.ts
  desktop/main/utils.ts
  desktop/main/walletFile.ts
Labels: bug

#1305 Fix renaming walletFile and bring tests back into CI
  .github/workflows/pr-build.yml
  .github/workflows/release.yml
  desktop/main/walletFile.ts
  tests/walletFiles.spec.ts
Labels: bug, milestone/genesis
