Repository spacemeshos/smapp, pull requests merged in 2023-01, with the labels that each got.

#1070 Fix bugs with switching between wallet modes
  app/components/NetworkStatus/NetworkStatus.tsx
  app/components/node/SmesherLog.tsx
  app/components/transactions/RewardRow.tsx
  app/components/transactions/TxRow.tsx
  app/redux/auth/actions.ts
  app/redux/wallet/actions.ts
  app/redux/wallet/reducer.ts
  app/screens/auth/UnlockWallet.tsx
  app/screens/network/Network.tsx
  app/screens/node/Node.tsx
  app/screens/transactions/Transactions.tsx
  app/types/redux.ts
  desktop/AccountState.ts
  desktop/NetServiceFactory.ts
  desktop/NodeManager.ts
  desktop/NodeService.ts
  desktop/SmesherManager.ts
  desktop/SmesherService.ts
  desktop/TransactionManager.ts
  desktop/WalletManager.ts
  desktop/main/constants.ts
  desktop/main/reactions/spawnManagers.ts
  desktop/main/reactions/syncToRenderer.ts
  desktop/main/sources/smesherInfo.ts
  desktop/main/sources/wallet.ipc.ts
  desktop/storeService.ts
  shared/types/guards.ts
  shared/types/tx.ts
  shared/utils.ts
Labels: Status: Ready for code review

#1069 fix(auth): fix match 2 password error
  app/screens/auth/CreateWallet.tsx
Labels: Status: Ready for code review

#1040 release: Smapp 0.2.10
  package.json
Labels: Status: Work in progress, Type: Release

#1082 Feature: update API from 1.3 to 1.5.6
  app/basicComponents/Input.tsx
  app/basicComponents/Tooltip.tsx
  app/components/node/PoSSize.tsx
  app/components/node/PoSSummary.tsx
  app/redux/smesher/actions.ts
  app/redux/smesher/reducer.ts
  app/redux/smesher/selectors.ts
  app/screens/node/Node.tsx
  app/screens/node/NodeSetup.tsx
  app/types/redux.ts
  desktop/SmesherManager.ts
  desktop/SmesherService.ts
  desktop/main/smeshingOpts.ts
  desktop/sentry.ts
  proto/api_config.yaml
  proto/gateway.proto
  proto/gateway.ts
  proto/gateway_types.proto
  proto/gateway_types.ts
  proto/smesher_types.proto
  proto/spacemesh/v1/BroadcastPoetRequest.ts
  proto/spacemesh/v1/BroadcastPoetResponse.ts
  proto/spacemesh/v1/GatewayService.ts
  proto/spacemesh/v1/PostSetupOpts.ts
  shared/types/node.ts
  shared/types/smesher.ts
  shared/utils.ts
Labels: Type: Feature

#1090 Fix reconnecting GRPC clients
  app/screens/auth/UnlockWallet.tsx
  app/screens/network/Network.tsx
  desktop/AccountState.ts
  desktop/NetServiceFactory.ts
  desktop/NodeManager.ts
  desktop/NodeService.ts
  desktop/TransactionManager.ts
  shared/types/node.ts
  shared/utils.ts
Labels: bug, P1

#1091 Auto-switch PoS directory on switching network + PoS dropdown tweak
  app/screens/node/NodeSetup.tsx
  desktop/NodeManager.ts
  desktop/SmesherManager.ts
  desktop/main/NodeConfig.ts
  desktop/storeService.ts
  desktop/utils.ts
  shared/types/node.ts
  shared/utils.ts
Labels: bug, P1

#1099 Update `layer-duration` node config property due to changes in go-spacemesh
  desktop/main/reactions/syncToRenderer.ts
  desktop/main/reactions/views/networkView.ts
  node/use-version
  package.json
  shared/types/node.ts
  yarn.lock
Labels: P1
